ARG RUBY_VERSION=4.0.2
FROM docker.io/library/ruby:${RUBY_VERSION}-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      git \
      chromium \
      libpq-dev \
      libvips \
      libyaml-dev \
      nodejs \
      npm \
      pkg-config \
      postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3 \
    PORT=3000 \
    PUPPETEER_SKIP_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

COPY Gemfile Gemfile.lock ./
COPY vendor ./vendor

RUN gem install foreman && bundle install

COPY . .

ENTRYPOINT ["/rails/bin/docker-dev-entrypoint"]
CMD ["foreman", "start", "-f", "Procfile.docker.dev"]
